export const ORG_PATHS = {
  ORG: '/org/:orgId',
  ADD: '/add_org',
  ADD_TEAM: 'add_team',
  EDIT: 'edit',
  EDIT_BADGE: 'edit_badge',
  ADD_ORG_SEASON: 'add_org_season',
  ADD_GAME_WEEK: 'add_game_week',
  EDIT_ORG_SEASON: 'edit',
  ORG_SEASON_ADMIN: 'admin',
  ORG_SEASON: 'org_season/:orgSeasonId',
  ADD_RESULT: 'add_result',
  EDIT_RESULT: 'edit',
  RESULT: 'result/:resultId',
  ADD_COMPETITION: 'add_competition',
  EDIT_COMPETITION: 'edit_comp',
  COMPETITION: 'competition/:competitionId',
  ORG_ADMIN: 'org_admin',
  ADMIN_ORG_SEASON: 'org_season/:orgSeasonId',
  ADMIN_TEAM: 'team/:teamId',
  ADMIN_COMPETITION: 'competition/:competitionId',
} as const;
