import * as Types from '../../../types/__generated__/graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Fetch_Squad_StatsQueryVariables = Types.Exact<{
  teamId: Types.Scalars['String']['input'];
  seasonId: Types.Scalars['String']['input'];
  competitionId: Types.Scalars['String']['input'];
}>;


export type Fetch_Squad_StatsQuery = { stats: Array<{ __typename: 'TSquadStats', _id: string, name: string, nationality: string | null, dateOfBirth: string | null, apps: number, goals: number, assists: number, mvp: number, conceded: number, cleanSheets: number, goalsPerGame: number, assistsPerGame: number, concededPerGame: number, mvpPerGame: number }> };


export const Fetch_Squad_StatsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"FETCH_SQUAD_STATS"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"teamId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"seasonId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"competitionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"stats"},"name":{"kind":"Name","value":"SQUAD_STATS"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"teamId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"teamId"}}},{"kind":"Argument","name":{"kind":"Name","value":"seasonId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"seasonId"}}},{"kind":"Argument","name":{"kind":"Name","value":"competitionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"competitionId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"nationality"}},{"kind":"Field","name":{"kind":"Name","value":"dateOfBirth"}},{"kind":"Field","name":{"kind":"Name","value":"apps"}},{"kind":"Field","name":{"kind":"Name","value":"goals"}},{"kind":"Field","name":{"kind":"Name","value":"assists"}},{"kind":"Field","name":{"kind":"Name","value":"mvp"}},{"kind":"Field","name":{"kind":"Name","value":"conceded"}},{"kind":"Field","name":{"kind":"Name","value":"cleanSheets"}},{"kind":"Field","name":{"kind":"Name","value":"goalsPerGame"}},{"kind":"Field","name":{"kind":"Name","value":"assistsPerGame"}},{"kind":"Field","name":{"kind":"Name","value":"concededPerGame"}},{"kind":"Field","name":{"kind":"Name","value":"mvpPerGame"}}]}}]}}]} as unknown as DocumentNode<Fetch_Squad_StatsQuery, Fetch_Squad_StatsQueryVariables>;