steps:
  - id: 'Check codegen output'
    name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        npm ci
        # Prefer a checked-in schema file to avoid requiring introspection on production
        export CODEGEN_SCHEMA_PATH="./schema.graphql"
        if [ -n "$${CODEGEN_SCHEMA_PATH:-}" ] && [ ! -f "$${CODEGEN_SCHEMA_PATH}" ]; then
          echo "schema file '$${CODEGEN_SCHEMA_PATH}' not found. Add a schema.graphql to the repo or enable introspection on your GraphQL endpoint."
          exit 1
        fi
        npm run codegen
        git add -A
        if [ -n "$(git status --porcelain)" ]; then
          echo "Generated files are out-of-date. Run: npm run codegen && git add -A && git commit -m 'Update generated files'"
          git --no-pager status --porcelain
          exit 1
        fi

  - id: 'build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'VITE_ROOT_URL=${_VITE_ROOT_URL}',
        '--build-arg',
        'VITE_APP_VERSION=$COMMIT_SHA',
        '-t',
        'madrid-reds-web:$COMMIT_SHA',
        '.',
      ]

  - id: 'tag docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'tag',
        'madrid-reds-web:$COMMIT_SHA',
        'europe-southwest1-docker.pkg.dev/madrid-reds-369822/madrid-reds-docker-images/madrid-reds-web:$COMMIT_SHA',
      ]

  - id: 'push docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-southwest1-docker.pkg.dev/madrid-reds-369822/madrid-reds-docker-images/madrid-reds-web:$COMMIT_SHA',
      ]

  - id: 'deploy image'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'madrid-reds-web',
        '--image',
        'europe-southwest1-docker.pkg.dev/madrid-reds-369822/madrid-reds-docker-images/madrid-reds-web:$COMMIT_SHA',
        '--region',
        'northamerica-northeast2',
        '--memory',
        '512Mi',
        '--port',
        '8080',
        '--allow-unauthenticated',
        '--cpu-throttling',
        '--set-env-vars',
        'VITE_ROOT_URL=${_VITE_ROOT_URL},VITE_APP_VERSION=$COMMIT_SHA',
      ]
