export const APP_ICONS = {
  MENU: 'menu',
  BACK: 'back',
  LOADING: 'loading',
  BADGE: 'badge',
  USER: 'user',
  DELETE: 'delete',
  LOCATION: 'location',
  FILTER: 'filter',
  MEDAL: 'medal',
  TROPHY: 'trophy',
  AWARD: 'star',
  OVERVIEW: 'overview',
  SQUAD: 'squad',
  MATCHES: 'results',
  HISTORY: 'history',
  NATIONALITY: 'nationality',
  CONFIRMED: 'confirmed',
  SUBMITTED: 'submitted',
  PENDING: 'pending',
  DISPUTED: 'disputed',
  CHECK: 'check',
  CROSS: 'cross',
  HELP: 'help',
  INFO: 'info',
  COPY: 'copy',
  COPIED: 'copied',
  FLAG: 'flag',
  SEARCH: 'search',
} as const;

export type AppIconType = (typeof APP_ICONS)[keyof typeof APP_ICONS];
