import * as Types from '../../../types/__generated__/graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Fetch_TeamQueryVariables = Types.Exact<{
  teamId: Types.Scalars['String']['input'];
}>;


export type Fetch_TeamQuery = { team: { __typename: 'Team', _id: string, teamName: string, yearFounded: string | null, location: string | null, country: string | null, homeShirt: string | null, homeShorts: string | null, homeSocks: string | null, awayShirt: string | null, awayShorts: string | null, awaySocks: string | null, kitsBackground: string | null, stadiumName: string | null, stadiumLocation: string | null, stadiumSurface: string | null, stadiumCapacity: string | null, isActive: boolean, teamRoles: Array<{ __typename: 'TeamRole', name: string, role: string, contact: string, roleId: string }>, teamBadge: { __typename: 'UploadedImage', url: string, public_id: string } | null, orgId: { __typename: 'Organization', _id: string, name: string, badge: { __typename: 'UploadedImage', public_id: string, url: string } } } };


export const Fetch_TeamDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"FETCH_TEAM"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"teamId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"team"},"name":{"kind":"Name","value":"FETCH_TEAM"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"teamId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"teamId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"teamName"}},{"kind":"Field","name":{"kind":"Name","value":"yearFounded"}},{"kind":"Field","name":{"kind":"Name","value":"location"}},{"kind":"Field","name":{"kind":"Name","value":"country"}},{"kind":"Field","name":{"kind":"Name","value":"homeShirt"}},{"kind":"Field","name":{"kind":"Name","value":"homeShorts"}},{"kind":"Field","name":{"kind":"Name","value":"homeSocks"}},{"kind":"Field","name":{"kind":"Name","value":"awayShirt"}},{"kind":"Field","name":{"kind":"Name","value":"awayShorts"}},{"kind":"Field","name":{"kind":"Name","value":"awaySocks"}},{"kind":"Field","name":{"kind":"Name","value":"kitsBackground"}},{"kind":"Field","name":{"kind":"Name","value":"stadiumName"}},{"kind":"Field","name":{"kind":"Name","value":"stadiumLocation"}},{"kind":"Field","name":{"kind":"Name","value":"stadiumSurface"}},{"kind":"Field","name":{"kind":"Name","value":"stadiumCapacity"}},{"kind":"Field","name":{"kind":"Name","value":"isActive"}},{"kind":"Field","name":{"kind":"Name","value":"teamRoles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"role"}},{"kind":"Field","name":{"kind":"Name","value":"contact"}},{"kind":"Field","name":{"kind":"Name","value":"roleId"}}]}},{"kind":"Field","name":{"kind":"Name","value":"teamBadge"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"public_id"}}]}},{"kind":"Field","name":{"kind":"Name","value":"orgId"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"badge"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"public_id"}},{"kind":"Field","name":{"kind":"Name","value":"url"}}]}}]}}]}}]}}]} as unknown as DocumentNode<Fetch_TeamQuery, Fetch_TeamQueryVariables>;