import * as Types from '../../../types/__generated__/graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Fetch_Player_StatsQueryVariables = Types.Exact<{
  playerId: Types.Scalars['String']['input'];
  seasonId: Types.Scalars['String']['input'];
  competitionId: Types.Scalars['String']['input'];
}>;


export type Fetch_Player_StatsQuery = { player: { __typename: 'PlayerStats', _id: string | null, apps: number | null, goals: number | null, assists: number | null, mvp: number | null, conceded: number | null, cleanSheet: number | null, ownGoals: number | null, pensMissed: number | null, pensSaved: number | null, pensScored: number | null, yellowCards: number | null, redCard: number | null, wins: number | null, draws: number | null, defeats: number | null, goalsFor: number | null, goalsAgainst: number | null, difference: number | null, gamesWithGoal: number | null, gamesWithAssist: number | null, gamesWithGoalAndAssist: number | null, gamesWithGoalOrAssist: number | null } };


export const Fetch_Player_StatsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"FETCH_PLAYER_STATS"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"playerId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"seasonId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"competitionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"player"},"name":{"kind":"Name","value":"PLAYER_STATS"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"playerId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"playerId"}}},{"kind":"Argument","name":{"kind":"Name","value":"seasonId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"seasonId"}}},{"kind":"Argument","name":{"kind":"Name","value":"competitionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"competitionId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"apps"}},{"kind":"Field","name":{"kind":"Name","value":"goals"}},{"kind":"Field","name":{"kind":"Name","value":"assists"}},{"kind":"Field","name":{"kind":"Name","value":"mvp"}},{"kind":"Field","name":{"kind":"Name","value":"conceded"}},{"kind":"Field","name":{"kind":"Name","value":"cleanSheet"}},{"kind":"Field","name":{"kind":"Name","value":"ownGoals"}},{"kind":"Field","name":{"kind":"Name","value":"pensMissed"}},{"kind":"Field","name":{"kind":"Name","value":"pensSaved"}},{"kind":"Field","name":{"kind":"Name","value":"pensScored"}},{"kind":"Field","name":{"kind":"Name","value":"yellowCards"}},{"kind":"Field","name":{"kind":"Name","value":"redCard"}},{"kind":"Field","name":{"kind":"Name","value":"wins"}},{"kind":"Field","name":{"kind":"Name","value":"draws"}},{"kind":"Field","name":{"kind":"Name","value":"defeats"}},{"kind":"Field","name":{"kind":"Name","value":"goalsFor"}},{"kind":"Field","name":{"kind":"Name","value":"goalsAgainst"}},{"kind":"Field","name":{"kind":"Name","value":"difference"}},{"kind":"Field","name":{"kind":"Name","value":"gamesWithGoal"}},{"kind":"Field","name":{"kind":"Name","value":"gamesWithAssist"}},{"kind":"Field","name":{"kind":"Name","value":"gamesWithGoalAndAssist"}},{"kind":"Field","name":{"kind":"Name","value":"gamesWithGoalOrAssist"}}]}}]}}]} as unknown as DocumentNode<Fetch_Player_StatsQuery, Fetch_Player_StatsQueryVariables>;