import * as Types from '../../../../types/__generated__/graphql';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Fetch_League_TablesQueryVariables = Types.Exact<{
  orgId: Types.Scalars['String']['input'];
  orgSeasonId: Types.Scalars['String']['input'];
}>;


export type Fetch_League_TablesQuery = { data: Array<{ __typename: 'LeagueTableByComp', splitIndexes: Array<number> | null, promotionPositions: Array<number> | null, relegationPositions: Array<number> | null, priority: number | null, competition: { __typename: 'ResultCompetiton', _id: string, name: string }, data: Array<{ __typename: 'LeagueTableTeamData', played: number, wins: number, draws: number, losses: number, goalsFor: number, goalsAgainst: number, goalDiff: number, points: number, team: { __typename: 'ResultTeam', _id: string, teamName: string } }> }> };


export const Fetch_League_TablesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"FETCH_LEAGUE_TABLES"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"orgId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"orgSeasonId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"data"},"name":{"kind":"Name","value":"LEAGUE_TABLE_DATA"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"orgId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"orgId"}}},{"kind":"Argument","name":{"kind":"Name","value":"orgSeasonId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"orgSeasonId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"competition"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"splitIndexes"}},{"kind":"Field","name":{"kind":"Name","value":"promotionPositions"}},{"kind":"Field","name":{"kind":"Name","value":"relegationPositions"}},{"kind":"Field","name":{"kind":"Name","value":"priority"}},{"kind":"Field","name":{"kind":"Name","value":"data"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"team"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"teamName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"played"}},{"kind":"Field","name":{"kind":"Name","value":"wins"}},{"kind":"Field","name":{"kind":"Name","value":"draws"}},{"kind":"Field","name":{"kind":"Name","value":"losses"}},{"kind":"Field","name":{"kind":"Name","value":"goalsFor"}},{"kind":"Field","name":{"kind":"Name","value":"goalsAgainst"}},{"kind":"Field","name":{"kind":"Name","value":"goalDiff"}},{"kind":"Field","name":{"kind":"Name","value":"points"}}]}}]}}]}}]} as unknown as DocumentNode<Fetch_League_TablesQuery, Fetch_League_TablesQueryVariables>;